### ISSUE TITLE
Quartz select dropdown white text on white background

### ISSUE THREAD

**Issue by skylarmt** [thomaspark/bootswatch#1118]
When using the Quartz theme, dropdown options are displaying with white text on a white background.

**Comment by skylarmt** [comment]
Adding this fixes it:

```css
select option {
    color: var(--bs-dark);
}
```
