### ISSUE TITLE
Cyborg: .list-group-item:hover bug on any list group item that's not the first

### ISSUE THREAD

**Issue by levu42** [thomaspark/bootswatch#1125]
Any list-group-item that's not the first has no top border, making the hover effect a bit strange looking.

It can be fixed by:

```css
.list-group-item + .list-group-item:hover {
  border-top-width: 1px;
  top: -1px;
}
```
