### ISSUE TITLE
Vapor no-repeat

### ISSUE THREAD

**Issue by Skwll** [thomaspark/bootswatch#1132]
Is there a simple way how I could make Vapor not repeat the background?
![opera_zNfEZmSwBI](https://user-images.githubusercontent.com/63907514/132417183-23efebb1-9958-4ad9-ade6-8d795ec53e4b.png)

**Comment by thomaspark** [comment]
You could add this to your CSS:

```css
body {
  background-repeat: no-repeat;
}
```

But if your body's larger than your viewport, it shouldn't be a problem as in the demo.
