### ISSUE TITLE
meteria: .tag is not BS and disrupts

### ISSUE THREAD

**Issue by AndersMad** [thomaspark/bootswatch#1209]
This is in the **materia** theme:
```css
.tag {
  padding: 4px 6px;
}
```
And I can't find that class in BS anywhere and it makes e.g. prismjs render bad. I believe `.tag` was a temp name in BS5 (now called badges).
