### ISSUE TITLE
Spruce,Spacelab style text-warning problem

### ISSUE THREAD

**Issue by unsalkorkmaz** [thomaspark/bootswatch#122]
in **Spruce & Spacelab style**;

``` css
.text-warning {
color: #fff;
}
```

becomes a problem because its not readable. I see there is more **color: #fff;** in spruce
