### ISSUE TITLE
Simplex icon opacity

### ISSUE THREAD

**Issue by unsalkorkmaz** [thomaspark/bootswatch#123]
why simplex have opacity on icons? is it intended?

``` css
i[class^="icon-"] {
vertical-align: -2px;
opacity: .5;
}
```
