### ISSUE TITLE
compile error in Materia theme with vite

### ISSUE THREAD

**Issue by mimmi20** [thomaspark/bootswatch#1298]
When running postcss and autoprefixer on the Materia theme with vite I got htis error

```shell
[vite:css] [postcss] 1.5em and 0 are incompatible.
     ╷
2092 │   min-height: calc(1.5em + 0 + calc(0 * 2));
     │                    ^^^^^^^^^
     ╵
  node_modules\bootswatch\dist\materia\bootstrap.css#sass 2092:20  root stylesheet
file: .../node_modules/bootswatch/dist/materia/bootstrap.css:2092:19
```

The themes Morph and Quartz work fine. I did not test other themes.

**Comment by thomaspark** [comment]
Can you check if this fixes it for you?

**Comment by mimmi20** [comment]
Now I get the error

```shell
[vite:css] [postcss] 3.5rem and 0 are incompatible.
     ╷
2443 │     height: calc(3.5rem + calc(0 * 2));
     │                  ^^^^^^^^^^^^^^^^^^^^
     ╵
  node_modules\bootswatch\dist\materia\bootstrap.css#sass 2443:18  root stylesheet
```

I found this in the compiled css file

```css
.form-floating > .form-select {
    height: calc(3.5rem + calc(0 * 2));
    min-height: calc(3.5rem + calc(0 * 2));
    line-height: 1.25;
}
```
