### ISSUE TITLE
SuperHero floating label in dark mode hwn

### ISSUE THREAD

**Issue by christopher-ayroso** [thomaspark/bootswatch#1314]

**Comment by thomaspark** [comment]
Here's how it looks for me:
![Screenshot 2024-09-30 at 9 21 24 AM](https://github.com/user-attachments/assets/90f75262-bf11-4a86-bc0f-feec93555488)

If you added a style to change the input background, you should be able to add another to make the label match. Something like:
```scss
.form-floating > .form-control:focus ~ label::after,
.form-floating > .form-control:not(:placeholder-shown) ~ label::after,
.form-floating > .form-control-plaintext ~ label::after,
.form-floating > .form-select ~ label::after {
  background-color: #000;
}
```
