### ISSUE TITLE
navbar-collapse @ rc-2

### ISSUE THREAD

**Issue by unsalkorkmaz** [thomaspark/bootswatch#135]
I see you have extra paddings in themes, even in default:

``` css
@media (min-width: 768px) {
.navbar-collapse {
padding-right: 0;
padding-left: 0;
}
}
```

Is it intended?

Update: nvm this. Too much change is still happening. I will re-open after 3.0 release if need
