### ISSUE TITLE
invalid border radius in Yeti theme

### ISSUE THREAD

**Issue by tomyam1** [thomaspark/bootswatch#196]
The Yeti theme produces some invalid border-radius properties:

``` css
.panel-heading {
  border-top-right-radius: -1;
  border-top-left-radius: -1;
}
.panel-footer {
  border-bottom-right-radius: -1;
  border-bottom-left-radius: -1;
}
```

This is usually not a problem, because these values are just ignored and radius=0 is the default, but I think it's best to add to Yeti's bootswatch.less:

``` css
.panel-heading, .panel-footer {
  border-top-right-radius: 0;
  border-top-left-radius: 0;
}
```
