### ISSUE TITLE
Flatly: Table Header Border Removed

### ISSUE THREAD

**Issue by Panman82** [thomaspark/bootswatch#221]
I'm not sure if this affects other themes but [line 5766](https://github.com/thomaspark/bootswatch/blob/gh-pages/flatly/bootstrap.css#L5766) overrides [line 1427](https://github.com/thomaspark/bootswatch/blob/gh-pages/flatly/bootstrap.css#L1427) and causes the table headers' bottom border to be removed. Looking at the [Bootstrap table docs](http://getbootstrap.com/css/#tables), I think the border should be kept. I would imagine this also affects `.table-bordered` too but have not tested it myself. Might just be a mater of positioning in the CSS file, if the block for line 5766 is really needed...

``` css
/* block for line 5766 */
table > thead > tr > th,
.table > thead > tr > th,
table > tbody > tr > th,
.table > tbody > tr > th,
table > tfoot > tr > th,
.table > tfoot > tr > th,
table > thead > tr > td,
.table > thead > tr > td,
table > tbody > tr > td,
.table > tbody > tr > td,
table > tfoot > tr > td,
.table > tfoot > tr > td {
  border: none;
}
```

``` css
/* block for line 1427 */
.table > thead > tr > th {
  vertical-align: bottom;
  border-bottom: 2px solid #ecf0f1;
}
```
