### ISSUE TITLE
Slate: Add Contexts for Badges

### ISSUE THREAD

**Issue by mikebronner** [thomaspark/bootswatch#259]
I would love to see contexts for badges added:
- badge-primary
- badge-info
- badge-success
- badge-warning
- badge-danger

I have added these myself so far using the following:

``` css
.badge.badge-default
{
    background-image: linear-gradient(#020202, #101112 40%, #191b1d);
}
.badge.badge-primary
{
    background-image: linear-gradient(#8a9196, #7a8288 60%, #70787d);
}
.badge.badge-success
{
    background-image: linear-gradient(#78cc78, #62c462 60%, #53be53);
}
.badge.badge-info
{
    background-image: linear-gradient(#74cae3, #5bc0de 60%, #4ab9db);
}
.badge.badge-warning
{
    background-image: linear-gradient(#faa123, #f89406 60%, #e48806);
}
.badge.badge-danger
{
    background-image: linear-gradient(#f17a77, #ee5f5b 60%, #ec4d49);
}
```
