### ISSUE TITLE
Close button inside panel-heading, flatly

### ISSUE THREAD

**Issue by HelloGravity** [thomaspark/bootswatch#266]
Hello !
I have noticed that close buttons inside panel-headings, look darker than inside alerts.
Fiddle : http://jsfiddle.net/e8Svx/
This is a problem, mainly with panel-primary.
I have found a css work-around : http://jsfiddle.net/HE8SQ/

``` css
.panel-heading .close {
      color: #fff;
      text-decoration: none;
      opacity: 0.4;
}
.panel-heading .close:hover,
.panel-heading .close:focus {
    color: #fff;
    opacity: 1;
}
```
