### ISSUE TITLE
Slate / Unreadable uneditable inputs

### ISSUE THREAD

**Issue by lisandropuzzolo** [thomaspark/bootswatch#31]
On slate theme, the uneditable inputs are unreadable.
Possible fix:

``` css
.uneditable-input, input[disabled], select[disabled], textarea[disabled], input[readonly], select[readonly], textarea[readonly] {
color: #fff
}
```
