### ISSUE TITLE
Darkly template, col-xs-12 not centering

### ISSUE THREAD

**Issue by jancel** [thomaspark/bootswatch#367]
See this issue live at http://demo.picturethis.io/

Here is the building (SLIM) html

``` slim
div.container

  div.dropzone-holder
    div.row.col-xs-12
      / Dropzone button
      form [method="post" enctype="multipart/form-data" ng-dropzone dropzone="single" dropzone-config="dropzoneConfigSingle" action="/pictures"]
        div#dropzoneSingle.camera-button.dropzone-button.img-rounded.text-center
          div.icon-for-dz
            i.fa.fa-camera
          |Single
    div.row.col-xs-12
      / Dropzone button
      form [method="post" enctype="multipart/form-data" ng-dropzone dropzone="multi" dropzone-config="dropzoneConfigMultiple" action="/pictures"]
        div#dropzoneMultiple.album-button.dropzone-button.img-rounded.text-center
          div.icon-for-dz
            i.fa.fa-picture-o
          |Multiple
```

SCSS 

``` css
.dropzone-button {
  color: $gray-darker;
  background-color: #EEE;
  min-height: 30px;
  padding:12px;
  margin:10px;
  margin-top:30px;
  font-size: 25px;
  font-weight: bolder;
  font-family: 'blackjack', Arial, sans-serif;

  &:hover {
    cursor:pointer;
  }
}

.icon-for-dz {
  font-size: 60px;
}
```
