### ISSUE TITLE
Darkly: .table-striped background identical to panel background

### ISSUE THREAD

**Issue by bunjiboys** [thomaspark/bootswatch#373]
With the Darkly template, the striped n-th child background color is the same as the default panel background, which means that table-striped class on the table doesnt actually distinguish the table rows visually.

Example: http://jsfiddle.net/vo7pvus6/2/

Could be solved by either changing the default table-striped nth-child background to something slightly different, for example #404040 or by adding another class to specifically handling striped tables inside panels:

``` css
.panel .table-striped>tbody>tr:nth-child(odd) {
    background-color: #404040;
}
```
