### ISSUE TITLE
Paper: Flat buttons

### ISSUE THREAD

**Issue by jareware** [thomaspark/bootswatch#495]
Thanks for all the great work on the Paper theme, looks & works really nice!

I was wondering what would be the correct way to implement [flat buttons](https://www.polymer-project.org/1.0/components/paper-button/demo.html)? I don't think there's a 1:1 equivalent in [vanilla Bootstrap](http://getbootstrap.com/components/#btn-dropdowns-split), because both links and default buttons are kinda different...

**Comment by thomaspark** [comment]
`.btn-link` is fairly close to flat buttons and could be styled to match the default and disabled states in your link.

I wouldn't want to add custom classes like `.colored` or `no-ink`, but once the default style there, it should be easier to override it to get those as well.

**Comment by jareware** [comment]
True, but then `.btn-link` doesn't have the ripple. :)

This is what I ended up using (SCSS with Bourbon), works pretty nice:

```scss
.btn {

  &.btn-default.myapp-flat { // this special marker makes the "default" style completely flat
    border: none;
    box-shadow: none !important;
    background-color: transparent;

    &:active {
      @include background-image(radial-gradient(circle, rgba(0, 0, 0, 0.1) 10%, transparent 11%));
    }
  }
}
```
