### ISSUE TITLE
variable in bootswatch.less (instead of variables.less)

### ISSUE THREAD

**Issue by szkrd** [thomaspark/bootswatch#543]
We would like to override the *@web-font-path* variable (we are using the flatly theme), unfortunately it's not in the _variables.less_ file, but in _bootswatch.less_ (and the used immediately below).

```less
@web-font-path: "https://fonts.googleapis.com/css?family=Lato:400,700,400italic";
.web-font(@path) {
  @import url("@{path}");
}
.web-font(@web-font-path);
```

Shouldn't it be in variables? How would one be able to override it?
