### ISSUE TITLE
Javascript please?

### ISSUE THREAD

**Issue by Miniapple8888** [thomaspark/bootswatch#548]
I started creating a website using Darker's theme created by bootswatch (by the way, thanks for these amazing themes) and I included the css in my websites. Everything looks good but when I click on the "dropdown" on the navigation bar, the dropdown won't display. I wonder if this is due because there is no javascript file coming along with it.

**Comment by jgog** [comment]
> Bootswatch aims to only provide only themes with CSS customisation, no JS.

Please make sure you include the Bootstraps JS file on your page. You could just use [http://www.bootstrapcdn.com](http://www.bootstrapcdn.com)

**Comment by wifiextender** [comment]
If your point is minimalism you can go without jquery/bootstrapJS.

Here is what I use in my [javascript driven blog](https://wifiextender.github.io)

```javascript
    var daMenus = {

        // Navbar and dropdowns
        toggle: document.getElementsByClassName('navbar-toggle')[0],
        collapse: document.getElementsByClassName('navbar-collapse')[0],

        toggleMenu: function() { // Toggle if navbar menu is open or closed
            daMenus.collapse.classList.toggle('collapse');
        },

        // Close dropdowns when screen becomes big enough to switch to open by hover
        closeMenusOnResize: function() {
            if (document.body.clientWidth >= 768) {
                daMenus.collapse.classList.add('collapse');
            }
        },
    };
    document.window.addEventListener('resize', daMenus.closeMenusOnResize);
    daMenus.toggle.addEventListener('click', daMenus.toggleMenu, false);
```

css
```css
/*
 * Open dropdowns on hover instead of click.
 * Source: https://mpetroff.net/2015/03/bootstrap-navbar-without-jquery/
 */
@media (min-width: 768px) {
  .dropdown:hover {
    background: #e7e7e7;
  }
  .dropdown:hover > .dropdown-menu {
    display: block;
  }
}

/*
 * The following is needed since the dropdowns are <div> elements instead
 * of <a> elements
 */
.nav > li > div {
  position: relative;
  display: block;
  padding: 10px 15px;
  cursor: default;
}
.navbar-nav > li > div {
  padding-top: 15px;
  padding-bottom: 15px;
  line-height: 20px;
}
.navbar-default .navbar-nav > li > div {
  color: rgb(119, 119, 119);
}
.navbar-collapse.collapse {
  display: none;
}
.dropdown-open {
  background: #e7e7e7;
}
body {
padding-bottom: 20px;
}
img {
  max-width: 100%;
}
.navbar {
margin-bottom: 20px;
}
```
