### ISSUE TITLE
Google fonts

### ISSUE THREAD

**Issue by pythonmobile** [thomaspark/bootswatch#55]
I saw this issue closed, and wanted to bring your attention to it once agian:

Requesting stuff from https://fonts.googleapis.com/ is very slow, especially with SSL enabled - perhaps we should consider adding the fonts into the Git repo so that they can be served from the local server?

Its not just that, its also a security hazard, as far as I understand. 

Can you perhaps post a howto for newbies on how to get rid of google's fonts and serve them locally?

Thanks.

**Comment by ibell** [comment]
I'd like to ping this issue again.  I ran into exactly this issue, it is not nice to HAVE to have internet access to use the generated HTML pages.

**Comment by thomaspark** [comment]
For themes that use a custom font, `@web-path-font` variable was added a little while back, which you can set to a local copy in LESS or SASS (#507).

You could combine this with something like [grunt-local-googlefont](https://www.npmjs.com/package/grunt-local-googlefont) to get what you need.

**Comment by bioteck** [comment]
And if you don't want to import any font? I use "Arial" so I don't need this import. But Bootswatch does not leave the choice:

```less
@web-font-path: "https://fonts.googleapis.com/css?family=Lato:400,700,400italic";

.web-font(@path) {
  @import url("@{path}");
}
.web-font(@web-font-path);
```

So I did this to clear the import:

```less
@web-font-path: '/empty.css';
```

But this is not a clean solution...
