### ISSUE TITLE
Megadrop in cosmo and others

### ISSUE THREAD

**Issue by gtbu** [thomaspark/bootswatch#781]
I am trying to match cosmo theme to typesetter-cms . My problem is how the new column in the megamenu under 'Themes'  is generated - the 
div class="dropdown-menu" aria-labelledby="themes"
                a class="dropdown-item" href="../default/">Def
                div class="dropdown-divider"></div>
                a class="dropdown-item"  give no hints.
Is it done by a js ? For any  help i would be thankful

**Comment by thomaspark** [comment]
You can add some custom CSS like this:

```css
.dropdown-menu.show[aria-labelledby="themes"] {
    display: flex;
    width: 420px;
    flex-wrap: wrap;
}

.dropdown-menu.show[aria-labelledby="themes"] .dropdown-item {
    width: 33.333%;
}
```
