### ISSUE TITLE
Double fieldset styles. 

### ISSUE THREAD

**Issue by massiws** [thomaspark/bootswatch#811]
In `cerulean/bootstrap.css` there are two different rules applied to `<fieldset>` and `<legend>` tags:

- around lines 174-182:
```css
fieldset {
  border: 1px solid #c0c0c0;
  margin: 0 2px;
  padding: 0.35em 0.625em 0.75em;
}
legend {
  border: 0;
  padding: 0;
}
```

Around lines 2494-2510:
```css
fieldset {
  padding: 0;
  margin: 0;
  border: 0;
  min-width: 0;
}
legend {
  display: block;
  width: 100%;
  padding: 0;
  margin-bottom: 20px;
  font-size: 21px;
  line-height: inherit;
  color: #555555;
  border: 0;
  border-bottom: 1px solid #e5e5e5;
}
```
I think only one is necessary.
