### ISSUE TITLE
Undefined variable $body-color in _bootswatch.scss when using flatly

### ISSUE THREAD

**Issue by akinstech** [thomaspark/bootswatch#817]
With the latest Bootswatch 4.1.0, I'm getting an Undefined variable $body-color in _bootswatch.scss when using the flatly theme.  The undefined variable is on line 171 within the .alert { } block.

```css
    &-light {
      &,
      & a,
      & .alert-link {
        color: $body-color;
      }
   }
```

I can set $body-color in my own code to work around the SASS build, but was wondering what it's supposed to be to maintain consistency with the theme?
