### ISSUE TITLE
Center div content

### ISSUE THREAD

**Issue by Flame-1** [thomaspark/bootswatch#840]
How to center a div?
![image](https://user-images.githubusercontent.com/40175769/41241311-2a01aeb8-6dcf-11e8-92d0-d7aad238c591.png)

**Comment by Flame-1** [comment]
![image](https://user-images.githubusercontent.com/40175769/41241868-a090f5e2-6dd0-11e8-95a1-4ce6fc5955e4.png)

![image](https://user-images.githubusercontent.com/40175769/41241911-ba2445fe-6dd0-11e8-9fa0-2d252cdfdfe2.png)

**Comment by thomaspark** [comment]
I recommend Stack Overflow's Bootstrap section for questions like this in the future. They're very helpful over there: https://stackoverflow.com/questions/tagged/twitter-bootstrap

But I'm happy to take a look. Can you post your code using JSFiddle or JSBin?

**Comment by Flame-1** [comment]
Yeah thank you
Check out: https://jsfiddle.net/dmajbtL8/
```css
.card {
  position: relative;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
      -ms-flex-direction: column;
          flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  background-color: #4E5D6C;
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 0;
  margin: auto;
  align-items: center;
}
```
