### ISSUE TITLE
Some fix suggestions

### ISSUE THREAD

**Issue by unsalkorkmaz** [thomaspark/bootswatch#91]
Hi,
I released a WordPress GPL theme that using Bootswatch themes: [FirmaSite](http://theme.firmasite.com/)
You can change style of that website from top-right "Change Style" dropdown menu and pls check fixes i suggest below.

I believe some of my fixes for styles that need to push for all bootswatch themes:

**cosmo theme:**

``` css
.label {
    min-width:inherit;
    min-height:inherit;
}
```

**superhero theme:**

``` css
.pager a { color:#e36b23; background-color: inherit; }
.pager li>a, .pager li>span { background-color: #5a6a7d; }
```

**slate**, **cyborg** and **superhero** themes are dark styles so i changed icon color: 

``` css
    /* Icon color fix for dark-colored styles */ 
    [class^="icon-"], [class*=" icon-"]{ 
            background-image:url("../img/glyphicons-halflings-white.png"); 
    } 
    .icon-white { 
            background-image:url("../img/glyphicons-halflings.png"); 
    } 

```

**journal theme:**

``` css
.dropdown-submenu>.dropdown-menu { top: 0; }
.dropup.navbar .dropdown-menu { top: auto; bottom: 85%; }
.dropup .dropdown-submenu>.dropdown-menu { bottom: 0; }
```

**amelia theme:**

``` css
.muted {color: #aaa;}
.muted.well, .well .muted {color: #fff;}
body {color: #444;}
legend, label, .help-block, .input-file { color: inherit; }
```

**spruce theme:**

``` css
.muted {color: #555;}
.modal,
.modal h1,
.modal h2,
.modal h3,
.modal h4,
.modal h5,
.modal h6{ color: #C4C4C4; }
```
