### ISSUE TITLE
Strange bg-dark setting for Darkly theme

### ISSUE THREAD

**Issue by seanhogge** [thomaspark/bootswatch#915]
The Darkly theme's css has the following entry near the bottom:

```css
.bg-dark {
  background-color: #00bc8c !important;
}
```

This is the bg-success color.
